development: &DEVELOPMENT
  adapter: postgresql
  database: status_development
  host: localhost
  pool: 5
  timeout: 5000

staging:
  <<: *DEVELOPMENT

test: &TEST
  <<: *DEVELOPMENT
  database: status_test
  min_messages: warning

cucumber:
  <<: *TEST

production:
  adapter: postgresql
  database: status_production
